NeerajraiInfra/Controllers/TraditionalAssociateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeerajraiInfra.Models;
using System.Data;
using NeerajraiInfra.Filter;
using System.Web.Script.Serialization;
using System.Net;
using System.Net.Mail;
using System.IO;

namespace NeerajraiInfra.Controllers
{
    public class TraditionalAssociateController : AdminBaseController
    {

        #region AffiliateRegistration
        public ActionResult AssociateRegistration(string UserID)
        {
            TraditionalAssociate model = new TraditionalAssociate();
            try
            {
                if (UserID != null)
                {

                    model.UserID = Crypto.Decrypt(UserID);
                    //model.UserID = UserID;
                    DataSet dsPlotDetails = model.GetList();
                    if (dsPlotDetails != null && dsPlotDetails.Tables.Count > 0)
                    {
                        model.UserID = UserID;
                        model.SponsorID = dsPlotDetails.Tables[0].Rows[0]["SponsorId"].ToString();
                        model.LoginID = dsPlotDetails.Tables[0].Rows[0]["AssociateId"].ToString();
                        model.SponsorName = dsPlotDetails.Tables[0].Rows[0]["SponsorName"].ToString();
                        model.FirstName = dsPlotDetails.Tables[0].Rows[0]["FirstName"].ToString();
                        model.LastName = dsPlotDetails.Tables[0].Rows[0]["LastName"].ToString();
                        model.DesignationID = dsPlotDetails.Tables[0].Rows[0]["FK_DesignationID"].ToString();
                        model.DesignationName = dsPlotDetails.Tables[0].Rows[0]["DesignationName"].ToString();
                        model.BranchID = dsPlotDetails.Tables[0].Rows[0]["Fk_BranchId"].ToString();
                        model.Contact = dsPlotDetails.Tables[0].Rows[0]["Mobile"].ToString();
                        model.Email = dsPlotDetails.Tables[0].Rows[0]["Email"].ToString();
                        model.State = dsPlotDetails.Tables[0].Rows[0]["State"].ToString();
                        model.City = dsPlotDetails.Tables[0].Rows[0]["City"].ToString();
                        model.Address = dsPlotDetails.Tables[0].Rows[0]["Address"].ToString();
                        model.Pincode = dsPlotDetails.Tables[0].Rows[0]["PinCode"].ToString();
                        model.PanNo = dsPlotDetails.Tables[0].Rows[0]["PanNumber"].ToString();
                        model.BranchName = dsPlotDetails.Tables[0].Rows[0]["BranchName"].ToString();
                        //   ViewBag.Disabled = "disabled";
                        model.AdharNumber = dsPlotDetails.Tables[0].Rows[0]["AdharNumber"].ToString();
                        model.BankAccountNo = dsPlotDetails.Tables[0].Rows[0]["MemberAccNo"].ToString();
                        model.BankName = dsPlotDetails.Tables[0].Rows[0]["MemberBankName"].ToString();
                        model.BankBranch = dsPlotDetails.Tables[0].Rows[0]["MemberBranch"].ToString();
                        model.IFSCCode = dsPlotDetails.Tables[0].Rows[0]["IFSCCode"].ToString();
                        model.ProfilePic = dsPlotDetails.Tables[0].Rows[0]["ProfilePic"].ToString();
                        model.Signature = dsPlotDetails.Tables[0].Rows[0]["Signature"].ToString();
                    }
                }
                else
                {

                }

                #region ddlBranch
                TraditionalAssociate obj = new TraditionalAssociate();
                int count = 0;
                List<SelectListItem> ddlBranch = new List<SelectListItem>();
                DataSet dsBranch = obj.GetBranchList();
                if (dsBranch != null && dsBranch.Tables.Count > 0 && dsBranch.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dsBranch.Tables[0].Rows)
                    {
                        if (count == 0)
                        {
                            ddlBranch.Add(new SelectListItem { Text = "Select Branch", Value = "0" });
                        }
                        ddlBranch.Add(new SelectListItem { Text = r["BranchName"].ToString(), Value = r["PK_BranchID"].ToString() });
                        count = count + 1;
                    }
                }

                ViewBag.ddlBranch = ddlBranch;

                #endregion

                #region ddlDesignation

                int desgnationCount = 0;
                List<SelectListItem> ddlDesignation = new List<SelectListItem>();
                DataSet dsdesignation = obj.GetDesignationList();
                if (dsdesignation != null && dsdesignation.Tables.Count > 0 && dsdesignation.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dsdesignation.Tables[0].Rows)
                    {
                        if (desgnationCount == 0)
                        {
                            ddlDesignation.Add(new SelectListItem { Text = "Select Designation", Value = "0" });
                        }
                        ddlDesignation.Add(new SelectListItem { Text = r["DesignationName"].ToString(), Value = r["PK_DesignationID"].ToString() });
                        desgnationCount = desgnationCount + 1;
                    }
                }

                ViewBag.ddlDesignation = ddlDesignation;

                #endregion
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View(model);

        }

        public ActionResult GetSponsorName(string SponsorID)
        {
            try
            {
                TraditionalAssociate model = new TraditionalAssociate();
                model.LoginID = SponsorID;

                #region GetSiteRate
                DataSet dssponsor = model.GetAssociateList();
                if (dssponsor != null && dssponsor.Tables[0].Rows.Count > 0)
                {
                    model.SponsorName = dssponsor.Tables[0].Rows[0]["Name"].ToString();
                    model.UserID = dssponsor.Tables[0].Rows[0]["PK_UserID"].ToString();
                    model.SponsorDesignationID = dssponsor.Tables[0].Rows[0]["FK_DesignationID"].ToString();
                    model.Percentage = dssponsor.Tables[0].Rows[0]["Percentage"].ToString();
                    int desgnationCount = 0;

                    DataSet dsdesignation = model.GetDesignationList();
                    List<SelectListItem> ddlDesignation = new List<SelectListItem>();
                    if (dsdesignation != null && dsdesignation.Tables.Count > 0 && dsdesignation.Tables[0].Rows.Count > 0)
                    {
                        foreach (DataRow r in dsdesignation.Tables[0].Rows)
                        {
                            if (desgnationCount == 0)
                            {
                                ddlDesignation.Add(new SelectListItem { Text = "Select Designation", Value = "0" });
                            }
                            ddlDesignation.Add(new SelectListItem { Text = r["DesignationName"].ToString(), Value = r["PK_DesignationID"].ToString() });
                            desgnationCount = desgnationCount + 1;
                        }
                    }

                    // ViewBag.ddlDesignation = ddlDesignation;

                    model.ddlDesignation = ddlDesignation;
                    model.Result = "yes";
                }
                else
                {
                    model.SponsorName = "";
                    model.Result = "no";
                }
                #endregion

                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        [HttpPost]
        [ActionName("AssociateRegistration")]
        [OnAction(ButtonName = "btnRegistration")]
        public ActionResult AssociateRegistration(HttpPostedFileBase postedFile, HttpPostedFileBase postedFile1, TraditionalAssociate model)
        {
            string FormName = "";
            string Controller = "";
            try
            {
                Random rnd = new Random();
                int ctrPasword = rnd.Next(111111, 999999);
                model.Password = Crypto.Encrypt(ctrPasword.ToString());
                model.AddedBy = Session["Pk_AdminId"].ToString();
                if (postedFile != null)
                {
                    model.ProfilePic = "/images/ProfilePicture/" + Guid.NewGuid() + Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(Path.Combine(Server.MapPath(model.ProfilePic)));
                    Session["ProfilePic"] = model.ProfilePic;
                }
                if (postedFile1 != null)
                {
                    model.Signature = "/images/ProfilePicture/" + Guid.NewGuid() + Path.GetExtension(postedFile1.FileName);
                    postedFile1.SaveAs(Path.Combine(Server.MapPath(model.Signature)));

                }
                DataSet dsRegistration = model.AssociateRegistration();
                if (dsRegistration != null && dsRegistration.Tables.Count > 0)
                {
                    if (dsRegistration.Tables[0].Rows[0][0].ToString() == "1")
                    {
                        Session["DisplayNameConfirm"] = dsRegistration.Tables[0].Rows[0]["Name"].ToString();
                        Session["LoginIDConfirm"] = dsRegistration.Tables[0].Rows[0]["LoginId"].ToString();
                        Session["PasswordConfirm"] = Crypto.Decrypt(dsRegistration.Tables[0].Rows[0]["Password"].ToString());
                        Session["PKUserID"] = Crypto.Encrypt(dsRegistration.Tables[0].Rows[0]["PKUserID"].ToString());
                        string assocname = dsRegistration.Tables[0].Rows[0]["Name"].ToString();

NeerajraiInfra/Views/TraditionalAssociate/AdvisorDownlineDetail.cshtml
@model NeerajraiInfra.Models.TraditionalAssociate

@{
    ViewBag.Title = "AdvisorDownlineDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("AdvisorDownlineDetail", "TraditionalAssociate", FormMethod.Post, new { @id = "form1" }))
{
    <section class="section">
        <ul class="breadcrumb breadcrumb-style ">
            <li class="breadcrumb-item">
                <a href="#">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">Associate</li>
            <li class="breadcrumb-item">Associate Downline Details</li>
        </ul>
    </section>
    <div class="section-body">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Associate Downline Details</h4>

                   
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="input-field col m3 s12">
                            Associate Id
                            @Html.TextBoxFor(m => m.AssociateID, new { @class = "form-control", @Placeholder = "Search by Associate ID" })
                        </div>

                        <div class="input-field col m3 s12">
                            <br />
                            <input class="btn btn-success" type="submit" value="Search" id="btnSearch" name="Search" onclick="return validateform();" />
                        </div>
                    </div>
                    <br />
                    <div class="dt-responsive table-responsive">
                        <table id="basic-btn" class="table table-striped table-bordered nowrap">
                            <thead>
                                <tr>
                                    <th>S No.</th>
                                    <th>Associate ID</th>
                                    <th>Associate Name</th>
                                    <th>Rank Name</th>
                                    <th>Rank</th>
                                    <th>Branch Name</th>
                                    <th>Mobile Number</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.lstTrad != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.lstTrad)
                                        {
                                            <tr class="text-left">
                                                <td>@i</td>
                                                <td>@Item.AssociateID</td>
                                                <td>@Item.AssociateName  </td>
                                                <td>@Item.DesignationName </td>
                                                <td>@Item.Percentage</td>
                                                <td>@Item.BranchName</td>
                                                <td>@Item.Contact</td>

                                            </tr>
                                            i++;
                                        }
                                    }
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>S No.</th>
                                    <th>Associate ID</th>
                                    <th>Associate Name</th>
                                    <th>Rank Name</th>
                                    <th>Rank</th>
                                    <th>Branch Name</th>
                                    <th>Mobile Number</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
}
<script>
    function validateform() {
        $(".errortext").removeClass("errortext");
        if ($('#AssociateID').val() == '') {
            $("#AssociateID").addClass('errortext');
            $('#AssociateID').focus();
            alert("Please fill Associate ID");
            return false;
        }
        return true;
    }
</script>

NeerajraiInfra/Views/TraditionalAssociate/AdvisorUplineDetail.cshtml
@model NeerajraiInfra.Models.TraditionalAssociate

@{
    ViewBag.Title = "AdvisorUplineDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AdvisorUplineDetail", "TraditionalAssociate", FormMethod.Post, new { @id = "form1" }))
{

    <section class="section">
        <ul class="breadcrumb breadcrumb-style ">
            <li class="breadcrumb-item">
                <a href="#">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">Associate</li>
            <li class="breadcrumb-item">Associate Upline Details</li>
        </ul>
    </section>


    <div class="section-body">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Associate Upline Details</h4>

                   
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="input-field col m3 s12">
                            Associate Id
                            @Html.TextBoxFor(m => m.AssociateID, new { @class = "form-control", @Placeholder = "Search by Associate ID" })
                            <span class="form-bar"></span>
                        </div>

                        <div class="input-field col m3 s12">
                            <br />
                            <input class="btn btn-success" type="submit" value="Search" id="btnSearch" name="Search" onclick="return validateform();" />
                        </div>
                    </div>
                    <br />
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" data-page-length='50' id="tableExport" style="width:100%;">
                            <thead>
                                <tr>
                                    <th>S No.</th>
                                    <th>Associate ID</th>
                                    <th>Associate Name</th>
                                    <th>Rank Name</th>
                                    <th>Rank</th>
                                    <th>Branch Name</th>
                                    <th>Mobile Number</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.lstTrad != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.lstTrad)
                                        {
                                            <tr class="text-left">
                                                <td>@i</td>
                                                <td>@Item.AssociateID</td>
                                                <td>@Item.AssociateName  </td>
                                                <td>@Item.DesignationName </td>
                                                <td>@Item.Percentage</td>
                                                <td>@Item.BranchName</td>
                                                <td>@Item.Contact</td>

                                            </tr>
                                            i++;
                                        }
                                    }
                                }
                            </tbody>
                            
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
}



<script>


    function validateform() {
        $(".errortext").removeClass("errortext");


        if ($('#AssociateID').val() == '') {
            $("#AssociateID").addClass('errortext');
            $('#AssociateID').focus();
            alert("Please fill Associate ID");
            return false;
        }


        return true;
    }
</script>

NeerajraiInfra/Views/TraditionalAssociate/ConfirmRegistration.cshtml
@model NeerajraiInfra.Models.TraditionalAssociate

@{
    ViewBag.Title = "ConfirmRegistration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .bg-register {
        background: url(websitelinks/images/bg/login-bg.jpeg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        min-height: 100vh;
    }

    .user-account h1 {
        color: #2b2b2b;
        font-weight: 300;
        margin: 30px 0 20px;
    }

    .registration-block {
        background-color: rgba(256, 256, 256, 0.8);
        padding: 15px 40px;
    }

    h2.big-green {
        font-size: 35px;
        color: #77b43f;
        font-style: italic;
        /* text-transform: uppercase; */
        text-align: center;
        margin-bottom: 15px;
    }

    .wrapper-thanks h3, .wrapper-thanks h4, .wrapper-thanks h2 {
        margin-bottom: 15px;
    }

    .account-info.clearfix {
        margin-top: 20px;
        margin-bottom: 20px;
        padding: 10px 0;
    }

    .account-info .list-inline {
        margin: 0;
        padding: 0;
        text-align: center;
    }

        .account-info .list-inline li {
            display: inline-block;
        }

    span.border-box {
        border: 2px solid #77b43f;
        padding: 7px 5px;
        color: #4a9604;
        background: #f9f9f9;
    }

    .wrapper-thanks {
        width: 100%;
        padding-top: 30px;
        padding-bottom: 30px;
    }

    .animated-gif {
        width: 92px;
        height: 92px;
        border-radius: 50%;
        /* padding-right: 102px; */
        overflow: hidden;
        text-align: center;
        margin: 0 auto;
        line-height: 92px;
        border: 0px solid green;
    }
</style>
<style type="text/css">
    @@media (max-width:560px) {

        .account-info .list-inline li {
            display: inline-block;
            margin-top: 18px;
        }
    }
</style>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <section class="section">
            <ul class="breadcrumb breadcrumb-style ">
                <li class="breadcrumb-item">
                    <a href="#">
                        <i data-feather="home"></i>
                    </a>
                </li>
                <li class="breadcrumb-item">Associate</li>
                <li class="breadcrumb-item">Confirm Registration</li>
            </ul>
        </section>
            <div class="x_content">
                <div class="row">
                    <div class="col-lg-12">

                        <div class="card">
                            <div class="card-title">
                             

                                <a href="/TraditionalAssociate/AssociateRegistration" style="margin:20px;" class="btn btn-info btn-sm float-right" title="Next">Add New</a>
                                @*<a href="/AdminReports/PrintWelcomeLetter?id=@Session["PKUserID"]" style="margin-right:20px;" class="btn btn-info btn-sm float-right" title="Next">Print Letter</a>*@

                            </div>
                            <div class="card-content">

                                <div class="wrapper-thanks">
                                    <div class="animated-gif">
                                        <img src="../../images/XwHw.gif" alt="" style="width: 100px;" />
                                    </div>
                                    <h2 class="big-green">Congratulations !!</h2>
                                    <div class="clearfix text-center">
                                        <h3>Now you are a Neeraj rai Infra opc pvt. ltd. Associate</h3>

                                        <div class="account-info clearfix">
                                            <div class="clearfix text-left">
                                                <div class="col-md-12 account-info-text text-center">
                                                    <ul class="list-inline">
                                                        <li><span class="border-box">Name: @Session["DisplayNameConfirm"]</span></li>
                                                        <li><span class="border-box">Login ID: @Session["LoginIDConfirm"]</span></li>
                                                        <li><span class="border-box">Password:  @Session["PasswordConfirm"]</span></li>
                                                    </ul>
                                                </div>
                                            </div>

                                        </div>

                                        <div class="clearfix">
                                            <h2 class="big-green">Thank You!</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NeerajraiInfra/Views/TraditionalAssociate/LevelTree.cshtml
@model NeerajraiInfra.Crypto

@{
    ViewBag.Title = "LevelTree";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Tree</h4>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <div class="row">
                    <div class="col-md-12">
                        <!-- HTML5 Export Buttons table start -->
                        <div class="card">

                            <div class="card-block">
                                <iframe id="frm" src="~/AdminLevelTree.aspx" style="height:500px;border: 0px solid;width:100%"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NeerajraiInfra/Views/TraditionalAssociate/UpdateRank.cshtml
@model NeerajraiInfra.Models.TraditionalAssociate

@{
    ViewBag.Title = "UpdateRank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateRank", "TraditionalAssociate", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div id="divload" class="loader"></div>
    <section class="section">
        <ul class="breadcrumb breadcrumb-style ">
            <li class="breadcrumb-item">
                <a href="#">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">Associate</li>
            <li class="breadcrumb-item">Update Associate Rank</li>
        </ul>
    </section>
    <div class="section-body">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Update Associate Rank</h4>

                    <p style="color: red">
                        @TempData["UpdateRank"]
                        @*<br />
                        @TempData["AssociateDetails"]*@
                    </p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="input-field col m3 s12">
                          <label> Name</label>
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @Placeholder = "Name", @disabled="disabled" })
                        </div>

                        <div class="input-field col m3 s12">
                           <label> Old Designation</label>
                            @Html.TextBoxFor(m => m.OldDesignation, new { @class = "form-control", @Placeholder = "Old Designation", @disabled = "disabled" })
                            @Html.HiddenFor(m => m.PK_DesignationID)
                        </div>

                        <div class="input-field col m3 s12">
                            <label> Designation<span style="color:red">*</span></label>
                            @Html.DropDownListFor(m => m.DesignationID, new SelectList(ViewBag.ddlDesignation, "Value", "Text"), new { @class = "form-control", @onchange = "return onSiteChange();" })
                        </div>

                        @*<div class="input-field col m3 s12">
                            Remark<span style="color:red">*</span>
                             @Html.TextBoxFor(m => m.Remark, new { @class = "form-control", @Placeholder = "Remark" })
                         </div>*@
                    </div>

                    <div class="form-group row">
                        <div class="input-field col m6 s12 mt-3">
                                @Html.HiddenFor(m => m.UserID, new { @Value = @Model.UserID })
                                <input class="btn btn-success" type="submit" onclick="return validateform();" value="Update" id="update" name="update" />
                            <a class="btn btn-info" href="/TraditionalAssociate/AssociateList">Back To List</a>
                        </div>
                        <input type="hidden" id="UserType" value="@Session["UserType"]" />
                        <input type="hidden" id="UserTypeName" value="@Session["UserTypeName"]" />

                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/files/bower_components/jquery/js/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>
    $(document).ready(function () {
        $("#divload").css({ 'display': 'none' });
        var UserType = $('#UserType').val();
        var UserTypeName = $('#UserTypeName').val();
        if (UserType == 'Admin' && UserTypeName != 'Admin' && UserTypeName != "") {
            GetMenuDetails();
        }
    });
    function GetMenuDetails() {
        debugger
        var URL = "/TraditionalAssociate/AssociateRegistration";
        $.ajax({
            type: "POST",
            url: "/Master/GetMenuDetails",
            data: { URL: URL },
            dataType: "json",
            //contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var obj = jQuery.parseJSON(data);
                console.log(obj)
                for (var i = 0; i < obj.length; i++) {
                    if (obj[i].FormSave == true) {
                        $('#btnRegistration').show();

                        $("#btnRegistration").removeAttr('disabled');
                    }
                    else {
                        $('#btnRegistration').hide();

                        $("#btnRegistration").attr('disabled', 'disabled');
                    }
                    debugger
                    if (obj[i].FormUpdate == true && $('#PlotSizeID').val() != "") {
                        $('#btnUpdate').show();

                        $("#btnUpdate").removeAttr('disabled');
                    }
                    else {
                        $('#btnUpdate').hide();
                        $("#btnUpdate").attr('disabled', 'disabled');
                    }
                }
            },
            error: function () {
                alert("Error occured!!")
            }
        });
    }
  


    function validateform() {
        debugger;
       // $("#divload").css({ 'display': '' });
        $(".errortext").removeClass("errortext");
      
        if ($('#DesignationID').val() == '0') {
            $("#DesignationID").addClass('errortext');
            $('#DesignationID').focus();
            alert('Please choose designation for update !!')
            return false;
        }
        else {
            alert('Are you sure you want to update associate designation ?');
        }
        //if ($('#Remark').val() == '') {
        //    $("#Remark").addClass('errortext');
        //    $('#Remark').focus();
        //    return false;
        //}
        return true;
    }
</script>
<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #fff0f0 !important;
    }
</style>