NeerajraiInfra/Controllers/CustomerDashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeerajraiInfra.Models;
using NeerajraiInfra.Filter;
using NeerajraiInfra.Controllers;

namespace NeerajraiInfra.Controllers
{
    public class CustomerDashboardController : BaseController
    {
        // GET: CustomerDashboard
        public ActionResult CustomerDashboard()
        {
            //ViewBag.Name = Session["FullName"].ToString();
            CustomerDashboard newdata = new CustomerDashboard();
            try
            {
                newdata.LoginId = Session["LoginId"].ToString();
                DataSet Ds = newdata.GetDetails();
                ViewBag.TotalBooking = Ds.Tables[0].Rows[0]["TotalBooking"].ToString();
                ViewBag.TotalPaidAmount = Ds.Tables[0].Rows[0]["PaidAmount"].ToString();
                ViewBag.TotalPending = Ds.Tables[0].Rows[0]["PendingAmt"].ToString();
                ViewBag.TotalPlotAmount = Ds.Tables[0].Rows[0]["Plotamount"].ToString();
                List<CustomerDashboard> lstInst = new List<CustomerDashboard>();
                newdata.CustomerID = Session["Pk_userId"].ToString();
                DataSet dsInst = newdata.GetDueInstallmentList();
                if (dsInst != null && dsInst.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dsInst.Tables[0].Rows)
                    {
                        CustomerDashboard obj = new CustomerDashboard();

                        obj.CustomerID = r["PK_UserId"].ToString();
                        obj.CustomerLoginID = r["LoginId"].ToString();
                        obj.CustomerName = r["FirstName"].ToString();
                        obj.PlotNumber = r["PlotInfo"].ToString();
                        obj.InstallmentNo = r["InstallmentNo"].ToString();
                        obj.InstallmentAmount = r["InstAmt"].ToString();


                        lstInst.Add(obj);
                    }

                    newdata.ListInstallment = lstInst;
                }

                List<CustomerDashboard> lstNews = new List<CustomerDashboard>();
                newdata.NewsFor = "Customer";
                DataSet dsAssociate = newdata.GetNews();
                if (dsAssociate != null && dsAssociate.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dsAssociate.Tables[0].Rows)
                    {
                        CustomerDashboard obj = new CustomerDashboard();
                        //   obj.PK_BookingId = r["PK_UserId"].ToString();

                        obj.PK_NewsID = r["PK_NewsID"].ToString();
                        obj.NewsHeading = r["NewsHeading"].ToString();
                        obj.NewsBody = r["NewsBody"].ToString();

                        lstNews.Add(obj);
                    }
                    newdata.ListNEWS = lstNews;
                }
            }
            catch (Exception ex)
            {
                TempData["Dashboard"] = ex.Message;
            }
            return View(newdata);
        }
        public ActionResult GetGraphDetailsOfPlot()
        {
            List<CustomerDashboard> dataList = new List<CustomerDashboard>();
            DataSet Ds = new DataSet();
            DataTable dt = new DataTable();
            CustomerDashboard newdata = new CustomerDashboard();
            newdata.LoginId = Session["LoginId"].ToString();
            Ds = newdata.BindGraphDetails();
            if (Ds.Tables.Count > 0)
            {

                int count = 0;
                foreach (DataRow dr in Ds.Tables[0].Rows)
                {
                    CustomerDashboard details = new CustomerDashboard();


                    details.Total = (dr["Total"].ToString());
                    details.Status = (dr["Status"].ToString());


                    dataList.Add(details);

                    count++;
                }
            }
            return Json(dataList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetPlotBookingOnGraph()
        {

            List<CustomerDashboard> dataList3 = new List<CustomerDashboard>();
            DataSet Ds = new DataSet();
            DataTable dt = new DataTable();
            CustomerDashboard newdata = new CustomerDashboard();
            newdata.CustomerID = Session["Pk_userId"].ToString();

            Ds = newdata.GetDetailsForBarGraph();
            if (Ds.Tables.Count > 0)
            {
                ViewBag.TotalUsers = Ds.Tables[0].Rows.Count;
                int count = 0;
                foreach (DataRow dr in Ds.Tables[0].Rows)
                {
                    CustomerDashboard details = new CustomerDashboard();


                    details.TotalBooking = (dr["TotalBooking"].ToString());
                    details.Month = (dr["Month"].ToString());


                    dataList3.Add(details);

                    count++;
                }
            }
            return Json(dataList3, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetStateCity(string Pincode)
        {
            try
            {
                Common model = new Common();
                model.Pincode = Pincode;

                #region GetStateCity
                DataSet dsStateCity = model.GetStateCity();
                if (dsStateCity != null && dsStateCity.Tables[0].Rows.Count > 0)
                {
                    model.State = dsStateCity.Tables[0].Rows[0]["State"].ToString();
                    model.City = dsStateCity.Tables[0].Rows[0]["City"].ToString();
                    model.Result = "yes";
                }
                else
                {
                    model.State = model.City = "";
                    model.Result = "no";
                }
                #endregion
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }


        #region CustomerBookings
        public ActionResult GetSiteDetails(string SiteID)
        {
            try
            {
                Plot model = new Plot();
                model.SiteID = SiteID;

                #region GetSectors
                List<SelectListItem> ddlSector = new List<SelectListItem>();
                model.Result = "yes";
                DataSet dsSector = model.GetSectorList();

                if (dsSector != null && dsSector.Tables.Count > 0)
                {
                    foreach (DataRow r in dsSector.Tables[0].Rows)
                    {
                        ddlSector.Add(new SelectListItem { Text = r["SectorName"].ToString(), Value = r["PK_SectorID"].ToString() });

                    }
                }
                model.ddlSector = ddlSector;
                #endregion

                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public ActionResult GetBlockList(string SiteID, string SectorID)
        {
            List<SelectListItem> lstBlock = new List<SelectListItem>();
            Master model = new Master();
            model.SiteID = SiteID;
            model.SectorID = SectorID;
            DataSet dsblock = model.GetBlockList();

            #region ddlBlock
            if (dsblock != null && dsblock.Tables.Count > 0 && dsblock.Tables[0].Rows.Count > 0)
            {

                foreach (DataRow dr in dsblock.Tables[0].Rows)
                {
                    lstBlock.Add(new SelectListItem { Text = dr["BlockName"].ToString(), Value = dr["PK_BlockID"].ToString() });
                }

            }

            model.lstBlock = lstBlock;
            #endregion

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CustomerBookingList(CustomerDashboard model)
        {
            #region ddlSite
            int count1 = 0;
            List<SelectListItem> ddlSite = new List<SelectListItem>();
            DataSet dsSite = model.GetSiteList();
            if (dsSite != null && dsSite.Tables.Count > 0 && dsSite.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsSite.Tables[0].Rows)
                {
                    if (count1 == 0)
                    {
                        ddlSite.Add(new SelectListItem { Text = "Select Site", Value = "0" });
                    }
                    ddlSite.Add(new SelectListItem { Text = r["SiteName"].ToString(), Value = r["PK_SiteID"].ToString() });
                    count1 = count1 + 1;

                }
            }
            ViewBag.ddlSite = ddlSite;
            #endregion

            List<SelectListItem> ddlSector = new List<SelectListItem>();
            ddlSector.Add(new SelectListItem { Text = "Select Phase", Value = "0" });
            ViewBag.ddlSector = ddlSector;

            List<SelectListItem> ddlBlock = new List<SelectListItem>();
            ddlBlock.Add(new SelectListItem { Text = "Select Block", Value = "0" });
            ViewBag.ddlBlock = ddlBlock;
            return View(model);
        }

        [HttpPost]
        [ActionName("CustomerBookingList")]
        [OnAction(ButtonName = "Search")]
        public ActionResult BookingList(CustomerDashboard model)
        {
            model.LoginId = Session["LoginId"].ToString();
            List<CustomerDashboard> lst = new List<CustomerDashboard>();
            model.SiteID = model.SiteID == "0" ? null : model.SiteID;
            model.SectorID = model.SectorID == "0" ? null : model.SectorID;
            model.BlockID = model.BlockID == "0" ? null : model.BlockID;
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");

NeerajraiInfra/Views/CustomerDashboard/ChangePasswordCustomer.cshtml
@model NeerajraiInfra.Models.CustomerDashboard

@{
    ViewBag.Title = "ChangePasswordCustomer";
    Layout = "~/Views/Shared/CustomerLayout.cshtml";
}
@using (Html.BeginForm("ChangePasswordCustomer", "CustomerDashboard", FormMethod.Post, new { @id = "form1" }))
{
    <section class="section">
        <ul class="breadcrumb breadcrumb-style ">
            <li class="breadcrumb-item">
                <a href="#">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">Customer</li>
            <li class="breadcrumb-item">Change Password</li>
        </ul>
    </section>
    <div class="section-body">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Change Password</h4>
                    <p style="color: red">
                        @TempData["Login"]
                    </p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-6 col-md-4 col-lg-4">
                            <div class="form-group">
                                <label> Old Password <span style="color: red">*</span></label>
                                @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Password)
                            </div>
                        </div>
                        <div class="col-6 col-md-4 col-lg-4">
                            <div class="form-group">
                                <label> New Password<span style="color: red">*</span></label>
                                @Html.TextBoxFor(m => m.NewPassword, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-6 col-md-4 col-lg-4">
                            <div class="form-group">
                                <label> Confirm New Password<span style="color: red">*</span></label>
                                @Html.TextBoxFor(m => m.ConfirmNewPassword, new { @class = "form-control", @onchange = "return Check();" })
                            </div>
                        </div>
                        <div class="col-12 col-md-4 col-lg-4">
                            <div class="form-group">
                                <br />

                                <input class="btn cyan waves-effect waves-light left btn-primary" type="submit" value="Change" id="btnChange" name="Change" onclick="return validate();" />
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
}
<script src="../../vendors/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true,
        });
    });
    function validate() {
        $(".errortext").removeClass("errortext");
        if ($('#Password').val() == '') {
            $("#Password").addClass('errortext');
            $('#Password').focus();
            return false;
        }
        if ($('#NewPassword').val() == '') {
            $("#NewPassword").addClass('errortext');
            $('#NewPassword').focus();
            return false;
        }
        if ($('#ConfirmNewPassword').val() == '') {
            $("#ConfirmNewPassword").addClass('errortext');
            $('#ConfirmNewPassword').focus();
            return false;
        }

        return true;
    }

    function Check() {
        debugger
        if ($('#ConfirmNewPassword').val() != $('#NewPassword').val()) {

            alert("Confirm Password and new password should be same .")
            $('#ConfirmNewPassword').val('')
        }
    }
</script>

NeerajraiInfra/Views/CustomerDashboard/CustomerBookingList.cshtml
@model NeerajraiInfra.Models.CustomerDashboard

@{
    ViewBag.Title = "CustomerBookingList";
    Layout = "~/Views/Shared/CustomerLayout.cshtml";
}
@using (Html.BeginForm("CustomerBookingList", "CustomerDashboard", FormMethod.Post, new { @id = "form1" }))
{
    <section class="section">
        <ul class="breadcrumb breadcrumb-style ">
            <li class="breadcrumb-item">
                <a href="#">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">Reports</li>
            <li class="breadcrumb-item">Plot Booking Details</li>
        </ul>
    </section>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Plot Booking Details</h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @*<div class="col-12 col-md-3 col-lg-3">
                                    <div class="form-group">
                                        <label>Customer ID</label>
                                        @Html.TextBoxFor(m => m.CustomerID, new { @class = "form-control", @Placeholder = "Search by Customer ID" })
                                    </div>
                                </div>
                                <div class="col-12 col-md-3 col-lg-3">
                                    <div class="form-group">
                                        <label>Associate ID</label>
                                        @Html.TextBoxFor(m => m.AssociateID, new { @class = "form-control", @Placeholder = "Search by Associate ID" })

                                    </div>
                                </div>*@

                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>Booking No</label>
                                    @Html.TextBoxFor(m => m.BookingNumber, new { @class = "form-control", @Placeholder = "Booking No" })

                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>Select Site</label>
                                    @Html.DropDownListFor(m => m.SiteID, new SelectList(ViewBag.ddlSite, "Value", "Text"), new { @class = "form-control", @onchange = "return onSiteChange();" })
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>Select Phase</label>
                                    @Html.DropDownListFor(m => m.SectorID, new SelectList(ViewBag.ddlSector, "Value", "Text"), new { @class = "form-control", @onchange = "return onSectorChange();" })
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label> Select Block</label>
                                    @Html.DropDownListFor(m => m.BlockID, new SelectList(ViewBag.ddlBlock, "Value", "Text"), new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>Plot Number</label>
                                    @Html.TextBoxFor(m => m.PlotNumber, new { @class = "form-control", @Placeholder = "PlotNumber" })
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>From Date</label>
                                    @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "From Date", @readonly = "readonly" })

                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label>To Date</label>
                                    @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "To Date", @readonly = "readonly" })

                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <br />
                                    <input class="btn btn-primary mr-1" type="submit" value="Search" id="btnSearch" name="Search" />
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-bordered table-md" data-page-length='50' id="tableExport" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>S No.</th>
                                        <th>Booking No</th>
                                        @*<th>Customer Detail</th>
                                        <th>Associate Details</th>*@
                                        <th>Booking Date</th>
                                        <th>Plot Number</th>
                                        <th>Area</th>
                                        <th>Booking Status</th>
                                        <th>Booking Rate</th>
                                        <th>Plot Amt</th>
                                        <th>Discount</th>
                                        <th>Plot Rate</th>
                                        <th>Net Amt</th>
                                        <th>Paid Amt</th>
                                        <th>View</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstPlot != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstPlot)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.BookingNumber</td>
                                                    @*<td>@Item.CustomerName (@Item.CustomerLoginID)</td>
                                                    <td>@Item.AssociateName (@Item.AssociateLoginID)</td>*@
                                                    <td>@Item.BookingDate</td>
                                                    <td>@Item.PlotNumber</td>
                                                    <td>@Item.PlotArea</td>
                                                    <td>@Item.BookingStatus</td>
                                                    <td>@Item.PlotRate</td>
                                                    <td>@Item.PlotAmount</td>
                                                    <td>@Item.Discount</td>
                                                    <td>@Item.PlotRate</td>
                                                    <td>@Item.NetPlotAmount</td>
                                                    <td>@Item.PaidAmount</td>
                                                    <td><div class="badge badge-success badge-shadow"><a class="badge badge-success badge-shadow" href="/CustomerDashboard/LedgerReport?BookingNumber=@Item.BookingNumber"><span>View Ledger</span></a></div>


                                                </tr>
                                                i++;
                                            }
                                        }
                                    }

                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


}

<script src="~/files/bower_components/jquery/js/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">

<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true,

        });
    });
    function onSiteChange() {
        $("#divload").css({ 'display': '' });
        var value = $('#SiteID').val();
        var values = $('#SectorID').val();
        var tr = [];
        $.ajax({
            url: "/CustomerDashboard/GetSiteDetails",
            Type: "Get",
            DataType: "JSON",
            data: { SiteID: value },
            success: function (data) {
                $("#divload").css({ 'display': 'none' });
                var j = 1;
                if (data.Result == "yes") {
                    $('#Rate').val(data.Rate);
                    $("#SectorID").html(""); // clear before appending new list
                    $("#SectorID").empty();
                    $("#SectorID").append(
                          $('<option></option>').val(0).html('Select Phase'));
                    $.each(data.ddlSector, function (index, Sectorcount) {
                        $("#SectorID").append(
                              $('<option></option>').val(Sectorcount.Value).html(Sectorcount.Text));

                    });

                }
                else {
                    $("#SectorID").empty();
                    $('#Rate').val('');
                }


            }

        });

    }

    function onSectorChange() {

        $("#divload").css({ 'display': '' });
        var siteID = $('#SiteID').val();
        var sectorID = $('#SectorID').val();
        $.ajax({
            url: '/AssociateDashboard/GetBlockList', type: 'post', dataType: 'json',
            data: { 'SiteID': siteID, 'sectorID': sectorID },
            success: function (data) {
                $("#divload").css({ 'display': 'none' });
                $("#BlockID").html(""); // clear before appending new list
                $("#BlockID").empty();
                $("#BlockID").append(
                      $('<option></option>').val(0).html('Select Block'));
                $.each(data.lstBlock, function (index, BlockCount) {
                    $("#BlockID").append(
                          $('<option></option>').val(BlockCount.Value).html(BlockCount.Text));
                });

            }

        });
    }

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true,
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true,
    });
</script>